//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TehcnoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAssignments
    {
        public int AssignmentID { get; set; }
        public int RequestID { get; set; }
        public int ExecutorID { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
    
        public virtual Executors Executors { get; set; }
        public virtual RepairRequests RepairRequests { get; set; }
    }
}
